# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 100
  help: "Maximum number of epochs"

batch_size:
  value: 128
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  value: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk4519-utt65.txt
  help: |
    All paths to training list
    Q1 (293.735 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk4519-utt65.txt
    Q2 (399.000 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk3000-utt133.txt
    Q3 (391.040 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk1504-utt260.txt


train_path:
  help: "Directory to training data where speaker audio are stored"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb2/wav

    
eval_list:
  value:  /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk10-utt1266.txt
  help: |
    All paths to evaluation list
    Q1 (16.080 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk30-utt536.txt
    Q2 (14.300 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk20-utt715.txt
    Q3 (12.660 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk10-utt1266.txt


eval_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/wav
  help: |
    All paths to evaluation data
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb_flac/eval/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data
    


musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/exp_resnet_voxceleb_LR_0_001
  help: |
    Path to save the score.txt and models: exps/exp_resnet_voxceleb
    Ce que le prof m'a donné: exps/exp_resnet5 (même architecture, mais entraînement pas commencé au debut)    
    exps/exp_resnet_voxceleb

initial_model:
  value: ""
  help: |
    Path of the initial_model
    exps/exp_resnet5/model/model_0080.model
    exps/exp_resnet5/model/best.model

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  help: "Number of speakers"
  value: 5994
    
    

# Command
eval:
  value: false
  help: "Only do evaluation"

