# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 100
  help: "Maximum number of epochs"

batch_size:
  value: 64
  help: "Batch size"

n_cpu:
  value: 4
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  help: "All paths to training list"
  value: |
    db/voxceleb2/train_list.txt
    db/vietnam_celeb/vietnam-celeb-t.txt.edited 
    db/cn_celeb/CN-Celeb2_flac/liste.edited

train_path:
  help: "Directory to training data where speaker audio are stored"
  value: |
    db/voxceleb2/wav
    db/vietnam_celeb/data
    db/cn_celeb/CN-Celeb2_flac/wav
    
eval_list:
  help: "All paths to evaluation list"
  value: |
    db/voxceleb1/veri_test2.txt
    db/vietnam_celeb/vietnam-celeb-e.txt.edited
    db/cn_celeb/CN-Celeb_flac/eval/lists/trials.lst.edited

eval_path:
  help: "All paths to evaluation data"
  value: |
    db/voxceleb1/wav
    db/vietnam_celeb/data
    db/cn_celeb/CN-Celeb_flac/eval/wav/

musan_path:
  value: "db/musan_split"
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: "db/rirs_noises/RIRS_NOISES/simulated_rirs"
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: "exps/exp_fbank_multi"
  help: "Path to save the score.txt and models"

initial_model:
  value: ""
  help: "Path of the initial_model"

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  help: "Number of speakers"
  value: |
    5994
    880
    1996

feat_dim:
  value: 80
  help: |
    Dim of features
    Original fbank (80)
    Kiwano fbank (81)
    For SSL it'll be determined automatically

feat_type:
  value: fbank
  help: |
    Type of the extractor
    - fbank: for filterbank
    - wavlm: for wavlm
    - wav2vec2: for wav2vec2
    

is_2d:
  value: false
  help: "For 2d learnable weights"


model_name:
  value: "facebook/wav2vec2-base-960h"
  help: |
    The model name to use for training or evaluation.
    Available options:
    - For Wav2Vec2
    - facebook/wav2vec2-base-960h
    - facebook/wav2vec2-large-960h
    - facebook/wav2vec2-large-robust-ft-libri-960h
    - facebook/wav2vec2-large-960h-lv60-self
    - For WavLM
    - microsoft/wavlm-base
    - microsoft/wavlm-base-plus
    - microsoft/wavlm-base-plus-sv
    - microsoft/wavlm-base-sv
    - microsoft/wavlm-large
    
    

# Command
eval:
  value: false
  help: "Only do evaluation"

