# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 100
  help: "Maximum number of epochs"

batch_size:
  value: 64
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  value: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk4519-utt65.txt
  help: |
    All paths to training list
    Q1 (293.735 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk4519-utt65.txt
    Q2 (399.000 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk3000-utt133.txt
    Q3 (391.040 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/voxceleb-train-spk1504-utt260.txt


train_path:
  help: "Directory to training data where speaker audio are stored"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb2/wav

    
eval_list:
  value:  /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk10-utt1266.txt
  help: |
    All paths to evaluation list
    Q1 (16.080 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk30-utt536.txt
    Q2 (14.300 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk20-utt715.txt
    Q3 (12.660 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/voxceleb-eval-spk10-utt1266.txt


eval_path:
  help: "All paths to evaluation data"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/wav


musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/cleaned/exp_densenet_voxceleb_spk4519_utt65
  help: |
    Path to save the score.txt and models
    Q1: exp_densenet_voxceleb_spk4519_utt65
    Q2: exp_densenet_voxceleb_spk3000_utt133
    Q3: exp_densenet_voxceleb_spk1504_utt260

initial_model:
  value: ""
  help: |
    Path of the initial_model
    exps/exp_densenet/model/model_0001.model
    exps/exp_densenet/model/best.model

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  value: 4519
  help: |
    Number of speakers
    Q1: 4519
    Q2: 3000
    Q3: 1504

stride:
  value: 2
  help: |
    Stride for first convolution
    First version: 2 but too much division
    Second version: 1

pooling_mode:
  value: "std"
  help: "Pooling_mode"

growth_rate:
  value: 32
  help: "Growth rate"

num_init_features:
  value: 64
  help: "Number of channel init"


arch:
  value: "densenet37"
  help: |
    The architecture to use
    densenet37
    densenet121
    densenet161
    densenet169
    densenet201
    densenet264
    

# Command
eval:
  value: false
  help: "Only do evaluation"

