# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 200
  help: "Maximum number of epochs"

batch_size:
  value: 64
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  value: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/cn-celeb-train-spk1501-utt99.txt
  help: |
    All paths to training list
    Q1 (148.599 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/cn-celeb-train-spk1501-utt99.txt
    Q2 (218.436 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/cn-celeb-train-spk1002-utt218.txt
    Q3 (160.960 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/cn-celeb-train-spk503-utt320.txt


train_path:
  help: "Directory to training data where speaker audio are stored"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb2_flac/wav

    
eval_list:
  value:  /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/cn-celeb-eval-spk196-utt50.txt
  help: |
    All paths to evaluation list
    Q1 (9.800 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/cn-celeb-eval-spk196-utt50.txt
    Q2 (14.700 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/cn-celeb-eval-spk196-utt75.txt
    Q3 (19.600 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/cn-celeb-eval-spk196-utt100.txt
 

eval_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb_flac/eval/wav
  help: |
    All paths to evaluation data
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb_flac/eval/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data


musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/cleaned/exp_resnet_vietnam_celeb_spk1501_utt99
  help: |
    Path to save the score.txt and models
    Q1: exp_resnet_vietnam_celeb_spk1501_utt99
    Q2: exp_resnet_vietnam_celeb_spk1002_utt218
    Q3: exp_resnet_vietnam_celeb_spk503_utt320

initial_model:
  value: ""
  help: |
    Path of the initial_model
    exps/exp_resnet5/model/model_0080.model
    exps/exp_resnet5/model/best.model

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  value: 1501
  help: |
    Number of speakers
    Q1: 1501
    Q2: 1002
    Q3: 503
    
    

# Command
eval:
  value: false
  help: "Only do evaluation"

