# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 100
  help: "Maximum number of epochs"

batch_size:
  value: 64
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  help: "All paths to training list"
  value: |
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb2/train_list.txt.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/vietnam-celeb-t.txt.edited 
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb2_flac/liste.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2004/nist_sre_train2004_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2005/nist_sre_train2005_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2006/nist_sre_train2006_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2008/nist_sre_train2008_MASTER.edited

train_path:
  help: "Directory to training data where speaker audio are stored"
  value: |
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb2/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb2_flac/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2004
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2005
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2006
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-train2008
    
eval_list:
  help: "All paths to evaluation list"
  value: |
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/veri_test2.txt.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/vietnam-celeb-e.txt.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb_flac/eval/lists/trials.lst.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2004/nist_sre_test2004_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2005/nist_sre_test2005_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2006/nist_sre_test2006_MASTER.edited
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2008/nist_sre_test2008_MASTER.edited

eval_path:
  help: "All paths to evaluation data"
  value: |
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/voxceleb1/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/cn_celeb/CN-Celeb_flac/eval/wav
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2004
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2005
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2006
    /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/nist/nist-sre-test2008

musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/exp_resnet_multi_1cl_7cp
  help: "Path to save the score.txt and models"

initial_model:
  value: ""
  help: |
    Path of the initial_model
    exps/exp_resnet5/model/model_0079.model
    exps/exp_resnet_multi_1c/model/model_0001.model

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  help: "Number of speakers"
  value: |
    5994
    880
    1996
    310
    525
    599
    1319

# Command
eval:
  value: false
  help: "Only do evaluation"

