# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 200
  help: "Maximum number of epochs"

batch_size:
  value: 128
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  value: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/vietnam-celeb-train-spk223-utt91.txt
  help: |
    All paths to training list
    Q1 (8.671 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/vietnam-celeb-train-spk667-utt13.txt
    Q2 (19.393 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/vietnam-celeb-train-spk451-utt43.txt
    Q3 (20.293 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/vietnam-celeb-train-spk223-utt91.txt
    All: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/train/vietnam-celeb-train-clean-spk880.txt


train_path:
  help: "Directory to training data where speaker audio are stored"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data

    
eval_list:
  value:  /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/vietnam-celeb-eval-clean-spk18-utt511.txt
  help: |
    All paths to evaluation list
    Q1 (2.268 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/vietnam-celeb-eval-clean-spk54-utt42.txt
    Q2 (3.360 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/vietnam-celeb-eval-clean-spk36-utt110.txt
    Q3 (9.198 audio): /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/vietnam-celeb-eval-clean-spk18-utt511.txt
    All: /local_disk/helios/mmlamah/projects/ECAPA-TDNN/cleaned/eval/vietnam-celeb-eval-clean.txt


eval_path:
  help: "All paths to evaluation data"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data


musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/cleaned/exp_densenet37_vietnam_celeb_spk223_utt91
  help: |
    Path to save the score.txt and models
    Q1: exp_densenet121_vietnam_celeb_spk667_utt13 
    Q2: exp_densenet121_vietnam_celeb_spk451_utt43
    Q3: exp_densenet121_vietnam_celeb_spk223_utt91
    All: exps/cleaned/exp_densenet121_vietnam_celeb

initial_model:
  value: "exps/cleaned/exp_densenet37_vietnam_celeb_spk223_utt91/model/best_0046.model"
  help: |
    Path of the initial_model
    exps/exp_resnet5/model/model_0080.model
    exps/exp_resnet5/model/best.model

# Model and Loss settings
C:
  value: 1024
  help: "Channel size for the speaker encoder"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  value: 223
  help: |
    Number of speakers
    Q1: 667
    Q2: 451
    Q3: 223
    All: 880

stride:
  value: 2
  help: |
    Stride for first convolution
    First version: 2 but too much division
    Second version: 1

pooling_mode:
  value: "std"
  help: "Pooling_mode"

growth_rate:
  value: 32
  help: "Growth rate"

num_init_features:
  value: 64
  help: "Number of channel init"


arch:
  value: "densenet37"
  help: |
    The architecture to use
    densenet37
    densenet121
    densenet161
    densenet169
    densenet201
    densenet264
    

# Command
eval:
  value: true
  help: "Only do evaluation"

